#!/usr/bin/env ruby

name    "library"
version "0.1.0"
title   "Library"
summary "Objectifying the Ruby Library"

description <<-END
  The Library class encapsulates the essential nature 
  of a Ruby library --a location on disk from which
  scripts can be required.
END

authors "Trans <transfire@gmail.com>"
created "2006-12-10"

resources(
  "home" => "http://rubyworks.github.com/library",
  "code" => "http://github.com/rubyworks/library",
  "mail" => "http://groups.google.com/groups/rubyworks-mailinglist"
)

repositories(
  "upstream" => "git://github.com/rubyworks/library.git"
)

organization "Rubyworks"
copyrights   "2006 Rubyworks (BSD-2-Clause)"

